server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:6543/gym_db
    username: postgres
    password: qwe
  liquibase:
    change-log: classpath:db/changelog/master.yml
  flyway:
    enabled: false