url=jdbc:postgresql://localhost:3456/postgres
username=postgres
password=qwe
driver=org.postgresql.Driver

changeLogFile=src/main/resources/db/changelog/master.yaml
outputFile=target/liquibase-output.txt